name: C++ and Python Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip

      - name: Build C++ project
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .
        shell: bash

      - name: Move shared library to tests/CPPProject
        run: |
          mkdir -p tests/CPPProject
          if [[ $RUNNER_OS == "Linux" ]]; then
            mv build/libsegment_tree.so tests/CPPProject/
          else
            move build\libsegment_tree.dll tests\CPPProject\
          fi
        shell: bash

      - name: Set library path for ${{ matrix.os }}
        if: matrix.os == 'ubuntu-latest'
        run: echo "LD_LIBRARY_PATH=$PWD/build:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        shell: bash
      - name: Set DLL path for Windows
        if: matrix.os == 'windows-latest'
        run: echo "PATH=$PWD/build;%PATH%" >> $GITHUB_ENV
        shell: cmd

      - name: Run tests
        run: python -m unittest discover -s ./tests -p "*.py"
        env:
          LD_LIBRARY_PATH: ${{ env.LD_LIBRARY_PATH }}
          PATH: ${{ env.PATH }}
