name: Run Unit Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3

      # Шаг 3: Забилдить os для разных операционных систем
      - name: Install build tools (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y g++ make

      - name: Install build tools (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install mingw -y
          echo C:\ProgramData\chocolatey\lib\mingw\tools\install\bin >> $GITHUB_PATH

      - name: Build C++ library
        run: |
          g++ -shared -o CPPProject/libsegment_tree.so CPPProject/segment_tree.cpp -fPIC  # Для Linux
          if [[ $RUNNER_OS == 'Windows' ]]; then g++ -shared -o CPPProject/libsegment_tree.dll CPPProject/segment_tree.cpp; fi

      # Шаг 4: Устанавливаем зависимости
      - name: Install Python dependencies
        run: |
          python get-pip.py
          pip install pytest

      # Шаг 5: Запуск тестов
      - name: Run tests
        run: python testCPP.py
