name: Build and Test C++ and Python on Linux and Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Build and test on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install C++ build tools
        run: |
          sudo apt update
          sudo apt install -y g++ make python3-pip

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile C++ code (Linux)
        run: |
          g++ -shared -o CPPProject/libsegment_tree.so CPPProject/segment_tree.cpp -fPIC

      - name: Run Python unit tests
        run: |
          python3 -m unittest discover

  build-windows:
    name: Build and test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install C++ build tools
        run: |
          choco install visualcpp-build-tools

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Visual Studio build environment
        run: |
          & "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64

      - name: Compile C++ code (Windows)
        run: |
          cl /LD /EHsc CPPProject/segment_tree.cpp /link /out:CPPProject/libsegment_tree.dll

      - name: Run Python unit tests
        run: |
          python -m unittest discover
